# euler2.py
"""completed"""
# solves problem 2 for Project Euler

# Problem statement:
# Each new term in the Fibbonacci sequence is generated by summing the
# previous two terms. Starting with 1 and 2, the first ten terms will be
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.
# By considering the terms in the Fibbonacci sequence whose values do not
# exceed four million, find the sum of the even-valued terms.

# Generate the Fibbonacci sequence until we get a value exceeding 4e6

#Start with the first two terms
Fib1 = 1
Fib2 = 2
# create an accumulator
x = 0
while Fib2 < 4000000:

	# check to see if the last number in the sequence is even
	if Fib2 %2 == 0:
		# if it is, add it to the sum
		x += Fib2
	# add the last two numbers together and tack it on the end of the list
	temp = Fib2
	Fib2 += Fib1
	Fib1 = temp

print x
